# ARCHIVED

# -*- coding: utf-8 -*-
"""med_llm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124tyvz6gTWRY1Xd66AokNxTwI3PtOz2k
"""

# !pip install safetensors
# import transformers
# import torch

model_id = "HPAI-BSC/Llama3-Aloe-8B-Alpha"

pipeline = transformers.pipeline(
    "text-generation",
    model=model_id,
    # Remove torch_dtype and load_in_8bit for CPU execution
    # model_kwargs={"torch_dtype": torch.bfloat16, "load_in_8bit": True},
    device_map="cpu",  # Force the model to run on CPU
    # offload_folder="offload",  # Uncomment and specify a folder if you want to offload to disk
)

messages = [
    {"role": "system", "content": "You are an expert medical assistant named Aloe, developed by the High Performance Artificial Intelligence Group at Barcelona Supercomputing Center(BSC). You are to be a helpful, respectful, and honest assistant."},
    {"role": "user", "content": "Hello."},
]

prompt = pipeline.tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
)

terminators = [
    pipeline.tokenizer.eos_token_id,
    pipeline.tokenizer.convert_tokens_to_ids("<|eot_id|>")
]

outputs = pipeline(
    prompt,
    max_new_tokens=256,
    eos_token_id=terminators,
    do_sample=True,
    temperature=0.6,
    top_p=0.9,
)
print(outputs[0]["generated_text"][len(prompt):])